
#
# This file is autogenerated.
#

cimport c_tesselator

	#
	# Supplements:
	#


cdef class Tesselator:
    cdef const c_tesselator.TESStesselator * _this
    cdef int _polySize
    cdef int _vertexSize
    cdef int _elementType
    
    cpdef add_contour(self, contour)
    cpdef int tesselate(self, windingRule=?, elementType=?, int polySize=?, int vertexSize=?)
    
