
#
# This file is autogenerated.
#

cdef extern from "mcpp_lib.h":

	#
	# Defines:
	#


	#
	# Typedefs:
	#

	
	

	#
	# Enums:
	#

	ctypedef enum OUTDEST:
		OUT=0
		ERR=1
		DBG=2
		NUM_OUTDEST=3
	

	#
	# Structs:
	#


	#
	# Functions:
	#

	void mcpp_reset_def_out_func()
	void mcpp_use_mem_buffers(int tf)
	char * mcpp_get_mem_buffer(OUTDEST od)
	int mcpp_lib_main(int argc,char * * argv)